export const authTexts = {
  title: 'Yönetici Girişi',
  subtitle: 'Üniversite kullanıcı adınızla giriş yapın',
  ariaLabel: 'Yönetici giriş formu',
  logoAlt: 'Kurum logosu',
  usernameLabel: 'Kullanıcı adı',
  usernamePlaceholder: 'Örn. kurum kullanıcı adınız',
  passwordLabel: 'Şifre',
  passwordPlaceholder: '••••••••',
  submit: 'Giriş Yap',
  submitting: 'Giriş yapılıyor...',
  requiredError: 'Kullanıcı adı ve şifre zorunludur.',
  forgotPassword: 'Şifremi Unuttum',
  forgotPasswordHref: '#',
  rememberLabel: 'Oturumumu açık tut',
  captchaLabel: 'Yönetici bot doğrulaması',
  captchaPlaceholder: 'Yönetici doğrulama bileşeni burada olacak',
  trustSecure: 'Güvenli Bağlantı',
  trustSsl: '256-bit SSL',
}
