export const authTexts = {
  title: 'Öğretmen Girişi',
  subtitle: 'Akademik personel e-postanızla giriş yapın',
  ariaLabel: 'Öğretmen giriş formu',
  logoAlt: 'Kurum logosu',
  usernameLabel: 'E-posta',
  usernamePlaceholder: 'ad.soyad@ktun.edu.tr',
  passwordLabel: 'Şifre',
  passwordPlaceholder: '••••••••',
  submit: 'Giriş Yap',
  submitting: 'Giriş yapılıyor...',
  requiredError: 'E-posta ve şifre zorunludur.',
  forgotPassword: 'Şifremi Unuttum',
  forgotPasswordHref: '#',
  rememberLabel: 'Oturumumu açık tut',
  captchaLabel: 'Öğretmen bot doğrulaması',
  captchaPlaceholder: 'Öğretmen doğrulama bileşeni burada olacak',
  trustSecure: 'Güvenli Bağlantı',
  trustSsl: '256-bit SSL',
}
