// <auto-generated />
using System;
using BitirmeApi.DataAccess.Concrete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitirmeApi.DataAccess.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260410180000_ProgramLetterGradeRules")]
    partial class ProgramLetterGradeRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitirmeApi.Entity.Entities.AcademicTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.Property<string>("TermType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StartYear", "EndYear", "TermType")
                        .IsUnique();

                    b.ToTable("AcademicTerms");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ValueNumeric")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ValueText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("QuestionId", "SubmissionId")
                        .IsUnique();

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ProgramEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProgramEntityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.AssessmentComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("WeightPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("AssessmentComponents", t =>
                        {
                            t.HasCheckConstraint("CK_AssessmentComponent_WeightPercentage", "[WeightPercentage] IS NULL OR ([WeightPercentage] >= 0 AND [WeightPercentage] <= 100)");
                        });
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.AssessmentComponentOutcomeMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseLearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseLearningOutcomeId");

                    b.HasIndex("AssessmentComponentId", "CourseLearningOutcomeId")
                        .IsUnique();

                    b.ToTable("AssessmentComponentOutcomeMappings", t =>
                        {
                            t.HasCheckConstraint("CK_AssessmentComponentOutcomeMapping_Weight", "[Weight] >= 0 AND [Weight] <= 1");
                        });
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CloEvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AchievementScore")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("CombinedAchievementScore")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("CourseLearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal?>("SurveyDifference")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("SurveyScore")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseLearningOutcomeId");

                    b.HasIndex("ExamId");

                    b.HasIndex("CourseOfferingId", "CourseLearningOutcomeId", "ResultType")
                        .IsUnique();

                    b.ToTable("CloEvaluationResults");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CloPoMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseLearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgramOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramOutcomeId");

                    b.HasIndex("CourseLearningOutcomeId", "ProgramOutcomeId")
                        .IsUnique();

                    b.ToTable("CloPoMaps");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ProgramEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProgramEntityId", "Code")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CourseEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneralEvaluation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImprovementSuggestions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCalculationDirty")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProgramOutcomeEvaluation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentFeedbackEvaluation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId")
                        .IsUnique();

                    b.ToTable("CourseEvaluations");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CourseEvaluationLetterGradeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseEvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPassing")
                        .HasColumnType("bit");

                    b.Property<string>("LetterGrade")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MinimumFinalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseEvaluationId", "LetterGrade")
                        .IsUnique();

                    b.ToTable("CourseEvaluationLetterGradeRules", t =>
                        {
                            t.HasCheckConstraint("CK_LetterGradeRule_ScoreBounds", "[MinScore] >= 0 AND [MaxScore] <= 100");

                            t.HasCheckConstraint("CK_LetterGradeRule_ScoreRange", "[MaxScore] >= [MinScore]");
                        });
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ProgramLetterGradeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPassing")
                        .HasColumnType("bit");

                    b.Property<string>("LetterGrade")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MinimumFinalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ProgramEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProgramEntityId", "LetterGrade")
                        .IsUnique();

                    b.ToTable("ProgramLetterGradeRules", t =>
                        {
                            t.HasCheckConstraint("CK_ProgramLetterGradeRule_ScoreBounds", "[MinScore] >= 0 AND [MaxScore] <= 100");

                            t.HasCheckConstraint("CK_ProgramLetterGradeRule_ScoreRange", "[MaxScore] >= [MinScore]");
                        });
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CourseLearningOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Code")
                        .IsUnique();

                    b.ToTable("Clos");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CourseOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicTermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("PassingGrade")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("Quota")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("A");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcademicTermId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("CourseId", "AcademicTermId", "Section")
                        .IsUnique();

                    b.ToTable("CourseOfferings");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Enrolled");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("CourseOfferingId", "StudentId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseEvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<double>("WeightPercentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CourseEvaluationId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ExamEvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AverageTotalScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IncludedStudentCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxTotalScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("MinTotalScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("int");

                    b.Property<int>("PerfectScoreCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("CourseOfferingId", "ExamId")
                        .IsUnique();

                    b.ToTable("ExamEvaluationResults");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExamId", "QuestionNumber")
                        .IsUnique();

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ExamQuestionEvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AchievementRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid?>("AssessmentComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AverageScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExamQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IncludedStudentCount")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentComponentId");

                    b.HasIndex("ExamId");

                    b.HasIndex("ExamQuestionId");

                    b.HasIndex("CourseOfferingId", "AssessmentComponentId")
                        .IsUnique()
                        .HasFilter("[AssessmentComponentId] IS NOT NULL");

                    b.HasIndex("CourseOfferingId", "ExamQuestionId")
                        .IsUnique()
                        .HasFilter("[ExamQuestionId] IS NOT NULL");

                    b.ToTable("ExamQuestionEvaluationResults", t =>
                        {
                            t.HasCheckConstraint("CK_ExamQuestionEvalResult_SingleTarget", "([ExamQuestionId] IS NOT NULL AND [AssessmentComponentId] IS NULL) OR ([ExamQuestionId] IS NULL AND [AssessmentComponentId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ExamQuestionOutcomeMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseLearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseLearningOutcomeId");

                    b.HasIndex("ExamQuestionId", "CourseLearningOutcomeId")
                        .IsUnique();

                    b.ToTable("ExamQuestionOutcomeMappings", t =>
                        {
                            t.HasCheckConstraint("CK_ExamQuestionOutcomeMapping_Weight", "[Weight] >= 0 AND [Weight] <= 1");
                        });
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ProgramEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccreditationCycleYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ProgramOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ProgramEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramEntityId", "Code")
                        .IsUnique();

                    b.ToTable("ProgramOutcomes");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ProgramOutcomeContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContributionLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseEvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseLearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProgramOutcomeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CourseLearningOutcomeId");

                    b.HasIndex("CourseEvaluationId", "CourseLearningOutcomeId", "ProgramOutcomeCode")
                        .IsUnique();

                    b.ToTable("ProgramOutcomeContributions");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ProgramOutcomeEvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AchievementScore")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgramOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProgramOutcomeId");

                    b.HasIndex("CourseOfferingId", "ProgramOutcomeId")
                        .IsUnique();

                    b.ToTable("ProgramOutcomeEvaluationResults");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseLearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("McqOptionsCsv")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Options")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("ScaleMax")
                        .HasColumnType("int");

                    b.Property<int>("ScaleMin")
                        .HasColumnType("int");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("CourseLearningOutcomeId");

                    b.HasIndex("SurveyId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.StudentAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Score")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("ExamQuestionId", "EnrollmentId")
                        .IsUnique();

                    b.ToTable("StudentAnswers");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.StudentAssessmentComponentScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvaluatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Score")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("AssessmentComponentId", "EnrollmentId")
                        .IsUnique();

                    b.ToTable("StudentAssessmentComponentScores");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.StudentEvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("FinalScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("IncludedInStatistics")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<string>("LetterGrade")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal?>("MakeupScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("MidtermScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("SuccessGrade")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsedExamType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("CourseOfferingId", "EnrollmentId")
                        .IsUnique();

                    b.ToTable("StudentEvaluationResults");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IncludeInStatistics")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SurveyId", "UserId")
                        .IsUnique();

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Answer", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.Submission", "Submission")
                        .WithMany("Answers")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.AppUser", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.ProgramEntity", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Program");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.AssessmentComponent", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.AssessmentComponentOutcomeMapping", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.AssessmentComponent", "AssessmentComponent")
                        .WithMany("OutcomeMappings")
                        .HasForeignKey("AssessmentComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.CourseLearningOutcome", "CourseLearningOutcome")
                        .WithMany("AssessmentComponentMappings")
                        .HasForeignKey("CourseLearningOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssessmentComponent");

                    b.Navigation("CourseLearningOutcome");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CloEvaluationResult", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.CourseLearningOutcome", "CourseLearningOutcome")
                        .WithMany()
                        .HasForeignKey("CourseLearningOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.CourseOffering", "CourseOffering")
                        .WithMany("CloEvaluationResults")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CourseLearningOutcome");

                    b.Navigation("CourseOffering");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CloPoMap", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.CourseLearningOutcome", "CLO")
                        .WithMany("Maps")
                        .HasForeignKey("CourseLearningOutcomeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.ProgramOutcome", "PO")
                        .WithMany()
                        .HasForeignKey("ProgramOutcomeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CLO");

                    b.Navigation("PO");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Course", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.ProgramEntity", "Program")
                        .WithMany("Courses")
                        .HasForeignKey("ProgramEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CourseEvaluation", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.CourseOffering", "CourseOffering")
                        .WithOne("CourseEvaluation")
                        .HasForeignKey("BitirmeApi.Entity.Entities.CourseEvaluation", "CourseOfferingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseOffering");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CourseEvaluationLetterGradeRule", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.CourseEvaluation", "CourseEvaluation")
                        .WithMany("LetterGradeRules")
                        .HasForeignKey("CourseEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseEvaluation");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ProgramLetterGradeRule", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.ProgramEntity", "Program")
                        .WithMany("LetterGradeRules")
                        .HasForeignKey("ProgramEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CourseLearningOutcome", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.Course", "Course")
                        .WithMany("Clos")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CourseOffering", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.AcademicTerm", "AcademicTerm")
                        .WithMany("CourseOfferings")
                        .HasForeignKey("AcademicTermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.Course", "Course")
                        .WithMany("CourseOfferings")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.AppUser", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AcademicTerm");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Enrollment", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.CourseOffering", "CourseOffering")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.AppUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseOffering");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Exam", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.CourseEvaluation", "CourseEvaluation")
                        .WithMany("Exams")
                        .HasForeignKey("CourseEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseEvaluation");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ExamEvaluationResult", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.CourseOffering", "CourseOffering")
                        .WithMany("ExamEvaluationResults")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseOffering");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ExamQuestion", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ExamQuestionEvaluationResult", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.AssessmentComponent", "AssessmentComponent")
                        .WithMany()
                        .HasForeignKey("AssessmentComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BitirmeApi.Entity.Entities.CourseOffering", "CourseOffering")
                        .WithMany("ExamQuestionEvaluationResults")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.ExamQuestion", "ExamQuestion")
                        .WithMany()
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssessmentComponent");

                    b.Navigation("CourseOffering");

                    b.Navigation("Exam");

                    b.Navigation("ExamQuestion");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ExamQuestionOutcomeMapping", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.CourseLearningOutcome", "CourseLearningOutcome")
                        .WithMany("ExamQuestionMappings")
                        .HasForeignKey("CourseLearningOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.ExamQuestion", "ExamQuestion")
                        .WithMany("OutcomeMappings")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseLearningOutcome");

                    b.Navigation("ExamQuestion");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ProgramOutcome", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.ProgramEntity", "Program")
                        .WithMany("ProgramOutcomes")
                        .HasForeignKey("ProgramEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ProgramOutcomeContribution", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.CourseEvaluation", "CourseEvaluation")
                        .WithMany("ProgramOutcomeContributions")
                        .HasForeignKey("CourseEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.CourseLearningOutcome", "CourseLearningOutcome")
                        .WithMany()
                        .HasForeignKey("CourseLearningOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseEvaluation");

                    b.Navigation("CourseLearningOutcome");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ProgramOutcomeEvaluationResult", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.CourseOffering", "CourseOffering")
                        .WithMany("ProgramOutcomeEvaluationResults")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.ProgramOutcome", "ProgramOutcome")
                        .WithMany()
                        .HasForeignKey("ProgramOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseOffering");

                    b.Navigation("ProgramOutcome");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Question", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.CourseLearningOutcome", "CourseLearningOutcome")
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("CourseLearningOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BitirmeApi.Entity.Entities.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseLearningOutcome");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.StudentAnswer", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.Enrollment", "Enrollment")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.ExamQuestion", "ExamQuestion")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("ExamQuestion");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.StudentAssessmentComponentScore", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.AssessmentComponent", "AssessmentComponent")
                        .WithMany("StudentScores")
                        .HasForeignKey("AssessmentComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.Enrollment", "Enrollment")
                        .WithMany("ComponentScores")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssessmentComponent");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.StudentEvaluationResult", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.CourseOffering", "CourseOffering")
                        .WithMany("StudentEvaluationResults")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.Enrollment", "Enrollment")
                        .WithMany("EvaluationResults")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseOffering");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Submission", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.Survey", "Survey")
                        .WithMany("Submissions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitirmeApi.Entity.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Survey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Survey", b =>
                {
                    b.HasOne("BitirmeApi.Entity.Entities.CourseOffering", "CourseOffering")
                        .WithMany("Surveys")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseOffering");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.AcademicTerm", b =>
                {
                    b.Navigation("CourseOfferings");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.AssessmentComponent", b =>
                {
                    b.Navigation("OutcomeMappings");

                    b.Navigation("StudentScores");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Course", b =>
                {
                    b.Navigation("Clos");

                    b.Navigation("CourseOfferings");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CourseEvaluation", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("LetterGradeRules");

                    b.Navigation("ProgramOutcomeContributions");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CourseLearningOutcome", b =>
                {
                    b.Navigation("AssessmentComponentMappings");

                    b.Navigation("ExamQuestionMappings");

                    b.Navigation("Maps");

                    b.Navigation("SurveyQuestions");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.CourseOffering", b =>
                {
                    b.Navigation("CloEvaluationResults");

                    b.Navigation("CourseEvaluation");

                    b.Navigation("Enrollments");

                    b.Navigation("ExamEvaluationResults");

                    b.Navigation("ExamQuestionEvaluationResults");

                    b.Navigation("ProgramOutcomeEvaluationResults");

                    b.Navigation("StudentEvaluationResults");

                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Enrollment", b =>
                {
                    b.Navigation("ComponentScores");

                    b.Navigation("EvaluationResults");

                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Exam", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ExamQuestion", b =>
                {
                    b.Navigation("OutcomeMappings");

                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.ProgramEntity", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("LetterGradeRules");

                    b.Navigation("ProgramOutcomes");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Submission", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("BitirmeApi.Entity.Entities.Survey", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
